"""Load CH-benCHmark .tbl files into PostgreSQL using COPY.

Reads pipe-delimited .tbl files generated by chBenchmark_1_0 and
bulk-loads them into the target database.  Automatically creates
tables from ch_benchmark_schema.sql, loads data, then adds foreign
key constraints at the end (faster than loading with FKs in place).

Usage:
    python db_setup/load_ch_data.py --data-dir /tmp/ch_data \
        --dsn "postgresql://user:pass@host:port/db"
"""

import argparse
import os
import re
import time

import psycopg2

# Load order respects foreign key dependencies.
# Region/nation/supplier first (no FK deps), then warehouse→district→
# customer→item→stock→orders→new_order→order_line→history.
LOAD_ORDER = [
    ("region",     "REGION.tbl",     ["r_regionkey", "r_name", "r_comment"]),
    ("nation",     "NATION.tbl",     ["n_nationkey", "n_name", "n_regionkey", "n_comment"]),
    ("supplier",   "SUPPLIER.tbl",   ["su_suppkey", "su_name", "su_address", "su_nationkey",
                                       "su_phone", "su_acctbal", "su_comment"]),
    ("warehouse",  "WAREHOUSE.tbl",  ["w_id", "w_name", "w_street_1", "w_street_2",
                                       "w_city", "w_state", "w_zip", "w_tax", "w_ytd"]),
    ("district",   "DISTRICT.tbl",   ["d_id", "d_w_id", "d_name", "d_street_1", "d_street_2",
                                       "d_city", "d_state", "d_zip", "d_tax", "d_ytd",
                                       "d_next_o_id"]),
    ("item",       "ITEM.tbl",       ["i_id", "i_im_id", "i_name", "i_price", "i_data"]),
    ("customer",   "CUSTOMER.tbl",   ["c_id", "c_d_id", "c_w_id", "c_first", "c_middle",
                                       "c_last", "c_street_1", "c_street_2", "c_city",
                                       "c_state", "c_zip", "c_phone", "c_since", "c_credit",
                                       "c_credit_lim", "c_discount", "c_balance",
                                       "c_ytd_payment", "c_payment_cnt", "c_delivery_cnt",
                                       "c_data", "c_n_nationkey"]),
    ("stock",      "STOCK.tbl",      ["s_i_id", "s_w_id", "s_quantity",
                                       "s_dist_01", "s_dist_02", "s_dist_03", "s_dist_04",
                                       "s_dist_05", "s_dist_06", "s_dist_07", "s_dist_08",
                                       "s_dist_09", "s_dist_10", "s_ytd", "s_order_cnt",
                                       "s_remote_cnt", "s_data", "s_su_suppkey"]),
    ("history",    "HISTORY.tbl",    ["h_c_id", "h_c_d_id", "h_c_w_id", "h_d_id",
                                       "h_w_id", "h_date", "h_amount", "h_data"]),
    ("orders",     "ORDER.tbl",      ["o_id", "o_d_id", "o_w_id", "o_c_id", "o_entry_d",
                                       "o_carrier_id", "o_ol_cnt", "o_all_local"]),
    ("new_order",  "NEWORDER.tbl",   ["no_o_id", "no_d_id", "no_w_id"]),
    ("order_line", "ORDERLINE.tbl",  ["ol_o_id", "ol_d_id", "ol_w_id", "ol_number",
                                       "ol_i_id", "ol_supply_w_id", "ol_delivery_d",
                                       "ol_quantity", "ol_amount", "ol_dist_info"]),
]


def _split_schema(sql):
    """Split schema SQL into (tables, fk_constraints).

    Returns the DDL for DROP/CREATE TABLE statements separately from
    ALTER TABLE ... ADD FOREIGN KEY statements so that data can be
    bulk-loaded without FK checks, then constraints added at the end.
    """
    fk_lines = []
    table_lines = []
    in_alter = False
    for line in sql.splitlines(keepends=True):
        if re.match(r"^\s*ALTER\s+TABLE\s+", line, re.IGNORECASE):
            in_alter = True
            fk_lines.append(line)
        elif in_alter:
            # Continuation of ALTER statement or comments between ALTERs
            fk_lines.append(line)
            if ";" in line:
                in_alter = False
        else:
            table_lines.append(line)
    return "".join(table_lines), "".join(fk_lines)


def load_table(cur, table_name, tbl_path, columns):
    """Load a single .tbl file into a table using COPY."""
    if not os.path.exists(tbl_path):
        print(f"  WARNING: {tbl_path} not found, skipping {table_name}")
        return 0

    col_list = ", ".join(columns)
    copy_sql = f"COPY {table_name} ({col_list}) FROM STDIN WITH (FORMAT csv, DELIMITER '|', NULL '')"

    row_count = 0
    with open(tbl_path, "r") as f:
        # psycopg2's copy_expert handles the COPY protocol
        cur.copy_expert(copy_sql, f)
        cur.execute(f"SELECT COUNT(*) FROM {table_name}")
        row_count = cur.fetchone()[0]

    return row_count


def main():
    parser = argparse.ArgumentParser(
        description="Load CH-benCHmark .tbl files into PostgreSQL."
    )
    parser.add_argument(
        "--data-dir", required=True,
        help="Directory containing .tbl files from chBenchmark -csv",
    )
    parser.add_argument(
        "--dsn", required=True,
        help="PostgreSQL connection string",
    )
    parser.add_argument(
        "--no-fk", action="store_true",
        help="Skip adding foreign key constraints entirely.",
    )
    args = parser.parse_args()

    conn = psycopg2.connect(args.dsn)
    conn.autocommit = False
    cur = conn.cursor()

    # --- 1. Create tables (without FK constraints) ---
    schema_path = os.path.join(os.path.dirname(__file__), "ch_benchmark_schema.sql")
    fk_sql = ""
    if os.path.exists(schema_path):
        with open(schema_path, "r") as f:
            table_sql, fk_sql = _split_schema(f.read())
        print("Creating tables...")
        cur.execute(table_sql)
        conn.commit()
    else:
        print(f"WARNING: {schema_path} not found, assuming tables already exist")

    # --- 2. Bulk-load data (no FK checks) ---
    total_rows = 0
    t0 = time.time()

    print("Loading data...")
    for table_name, tbl_file, columns in LOAD_ORDER:
        tbl_path = os.path.join(args.data_dir, tbl_file)
        t1 = time.time()
        rows = load_table(cur, table_name, tbl_path, columns)
        elapsed = time.time() - t1
        print(f"  {table_name:>12}: {rows:>10,} rows  ({elapsed:.1f}s)")
        total_rows += rows
        conn.commit()

    elapsed_total = time.time() - t0
    print(f"\nLoaded {total_rows:,} total rows in {elapsed_total:.1f}s")

    # --- 3. Add foreign key constraints ---
    if not args.no_fk and fk_sql.strip():
        print("Adding foreign key constraints...")
        t1 = time.time()
        cur.execute(fk_sql)
        conn.commit()
        print(f"Foreign keys added in {time.time() - t1:.1f}s")

    cur.close()
    conn.close()


if __name__ == "__main__":
    main()
